version: "2.1"
services:
  astrobee:
    image: isaac:latest
    entrypoint: "/ros_entrypoint.sh"
    command: roslaunch isaac sim.launch gzserver:=false glp:=disabled dds:=false r2:=true
    hostname: astrobee
    container_name: astrobee
    expose:
      - 11311
    environment:
      - ROS_MASTER_URI=http://rosmaster:11311
      - ROS_IP=172.19.0.6
      - ROSLAUNCH_SSH_UNKNOWN=1
    networks:
      isaac:
        ipv4_address: 172.19.0.6

networks:
  isaac:
    external:
      name: isaac